In [1]:
import numpy as np
from math import sin, cos, degrees, radians as ra, pi
import matplotlib.pyplot as plt


bro = np.array([[1, -sin(ra(32))],
                [-0.20, cos(ra(32))]])

print(bro)
inversed_bro = np.linalg.inv(bro)
print(inversed_bro)

print(np.matmul(inversed_bro, np.array([[27*9.8], [0]])))



[[ 1.         -0.52991926]
 [-0.2         0.8480481 ]]
[[1.14282302 0.71411508]
 [0.26951844 1.34759222]]
[[302.39096987]
 [ 71.31458021]]


In [2]:

# mass of sun
S = 1.9886e30

# distance of earth to sun
D = 1.4960e11

# mass of earth
E = 5.9722e24

# Radius of earth
R = 6.3781e6

# Universal Gravitational constant
G = 6.67384e-11

# Mass of moon
M = 7.3477e22

# Radius of moon
N = 1.7374e6


In [12]:
from math import *

print(-G * .2 / .04 - G * .8 / .08)
-G * .2 * .001 / .08 - G * .8 *.001 / .04 - (-G * .2 * .001 / .04 - G * .8 *.001 / .08)

-1.001076e-09


-5.005379999999999e-13

$\implies \infty \arctan 10$

$ \frac{1}{s - 1} + \frac{1}{2} + 2\int_{0}^{\infty} \frac{\sin(s \arctan t)}{(1+t^2)^{s/2}(e^{2\pi t} - 1)} \, dt $

In [6]:
from typing import Union

x = np.linspace(0, 99, 100)

def integral(f, a, b, n):

    # using simpson's rule
    h = (b - a) / n
    s = f(a) + f(b)

    for i in range(1, n, 2):
        s += 4 * f(a + i * h)
    for i in range(2, n-1, 2):
        s += 2 * f(a + i * h)
    
    return s * h / 3


def f(x):
    return sin(x)

print(integral(f, 0, 10, 1000))





1.8390715291786217


In [8]:
from math import exp, pi

def f(x):
    return exp(-x) * sin(pi * x)

print(integral(f, 0, 1, 1000))

print((-exp(-1) * sin(pi * 1) - pi * exp(-1) * cos(pi * 1)) / (1 + pi**2) - (-exp(0) * sin(pi * 0) - pi * exp(0) * cos(pi * 0)) / (1 + pi**2))

0.3953520151066232
0.3953520151064591
